from matrix import *
from lu import *



A = matrix([[1,3,1,5],[2,8,1,2],[1,10,4,7],[1,2,3,4]])
A.invers().print()
print()
(invers(A)*A).print()
# print()
# A = matrix([[1,3,1,5],[2,8,1,2],[1,10,4,7]])
# print("A:")
# A.print()
# (L,U) = lu(A,False)
# print("L:")
# L.print()
# print("U:")
# U.print()
# # print("P:")
# # P.print()
# print("error:")
# print((A-L*U).norm())

# print()
# A = matrix([[1,3,1],[2,8,1],[1,10,4],[2,1,-2]])
# print("A:")
# A.print()
# (L,U) = lu(A,False)
# print("L:")
# L.print()
# print("U:")
# U.print()
# # print("P:")
# # P.print()
# print("error:")
# print((A-L*U).norm())